from pydantic import BaseModel, ConfigDict


class CategoryCreate(BaseModel):
    """What the API expects when creating a category - no id yet, since the database generates it."""

    name: str


class CategoryResponse(BaseModel):
    """What the API returns - includes the id generated by the database."""

    model_config = ConfigDict(from_attributes=True)

    id: int
    name: str
